language: r
cache: packages
sudo: required
dist: trusty

warnings_are_errors: true

r_packages:
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
  - covr
  - mnis
  - hansard
  - dplyr

apt_packages:
- libudunits2-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev libhdf5-7
  - gdal-config --version

after_success:
  - Rscript -e 'library(covr); codecov()'