language: r
cache: packages
sudo: required

warnings_are_errors: true

r_packages:
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
  - covr

addons:
  postgresql: "9.6"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev
  - gdal-config --version

after_success:
  - Rscript -e 'library(covr); codecov()'