# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
