language: r
r:
  - devel
  - release
cache: packages
sudo: required
dist: trusty

warnings_are_errors: true

r_packages:
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
  - covr
  - mnis
  - hansard
  - dplyr
  - leaflet
  - htmlwidgets
  - sf

apt_packages:
- libudunits2-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev libhdf5-7
  - sudo apt-get install -f
  - gdal-config --version

after_success:
  - Rscript -e 'library(covr); codecov()'